# Generated by Django 5.2.12 on 2026-04-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_scouting_permissions'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameIndex(
            model_name='scoutingreport',
            new_name='api_scoutin_submitt_9d2533_idx',
            old_name='api_scoutin_submitt_a4832d_idx',
        ),
        migrations.RenameIndex(
            model_name='scoutingreport',
            new_name='api_scoutin_farmer__7a98f1_idx',
            old_name='api_scoutin_farmer__6df7e4_idx',
        ),
    ]
