# Generated by Django 5.2.8 on 2026-03-25 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fix_admin_log_user_id_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('entity_type', models.CharField(choices=[('exporter', 'Exporter'), ('nursery', 'Nursery'), ('farm', 'Farm'), ('other', 'Other')], max_length=20)),
                ('company_name', models.CharField(max_length=255)),
                ('HCDA_license', models.CharField(max_length=100, unique=True)),
                ('license_expiry_date', models.DateField()),
                ('head_agronomist', models.CharField(max_length=255)),
                ('primary_county', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='entity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.entity'),
        ),
    ]
