# Generated by Django 5.2.8 on 2026-04-07 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyrecord',
            options={'ordering': ['-timestamp']},
        ),
    ]

