# Generated by Django 6.0.3 on 2026-04-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_seed_demo_operational_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='agronomist_compliance_status',
            field=models.CharField(choices=[('compliant', 'compliant'), ('needs-follow-up', 'needs-follow-up')], default='compliant', max_length=32),
        ),
    ]
