# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations, models
from django.utils import timezone


def _format_farmer_code(n: int, year: int) -> str:
    return f'FRM-{n:04d}-{year}'


def backfill_farmer_codes(apps, schema_editor):
    FarmerProfile = apps.get_model('api', 'FarmerProfile')
    FarmerCodeSequence = apps.get_model('api', 'FarmerCodeSequence')

    # Assign codes deterministically: oldest registration/user first.
    qs = FarmerProfile.objects.select_related('user').all()
    farmers = list(qs)

    def sort_key(fp):
        reg = getattr(fp, 'registration_date', None)
        if reg:
            return (reg, str(fp.id))
        user = getattr(fp, 'user', None)
        dj = getattr(user, 'date_joined', None)
        if dj:
            return (dj.date(), str(fp.id))
        return (timezone.now().date(), str(fp.id))

    farmers.sort(key=sort_key)

    counters: dict[int, int] = {}
    for fp in farmers:
        code = getattr(fp, 'farmer_code', None)
        if code:
            # Keep existing codes if already set.
            continue
        year = fp.registration_date.year if fp.registration_date else timezone.now().year
        counters[year] = counters.get(year, 0) + 1
        fp.farmer_code = _format_farmer_code(counters[year], year)
        fp.save(update_fields=['farmer_code'])

    # Ensure sequences are at least the highest issued number per year.
    for year, last_number in counters.items():
        obj, _ = FarmerCodeSequence.objects.get_or_create(year=year)
        if obj.last_number < last_number:
            obj.last_number = last_number
            obj.save(update_fields=['last_number'])

    # Also account for any pre-existing codes (if any) to prevent collisions.
    # Parse pattern: FRM-0001-2026
    existing = FarmerProfile.objects.exclude(farmer_code__isnull=True).exclude(farmer_code='').values_list('farmer_code', flat=True)
    parsed: dict[int, int] = {}
    for code in existing:
        try:
            parts = str(code).split('-')
            if len(parts) != 3:
                continue
            n = int(parts[1])
            y = int(parts[2])
            parsed[y] = max(parsed.get(y, 0), n)
        except Exception:
            continue
    for y, n in parsed.items():
        obj, _ = FarmerCodeSequence.objects.get_or_create(year=y)
        if obj.last_number < n:
            obj.last_number = n
            obj.save(update_fields=['last_number'])


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_farmerprofile_agronomist_compliance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='farmerprofile',
            name='farmer_code',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(backfill_farmer_codes, migrations.RunPython.noop),
    ]

