# Generated by Django 6.0.3 on 2026-04-21 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_farmerprofile_farmer_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmercodesequence',
            options={'ordering': ['year']},
        ),
    ]
