# Generated by Django 6.0.3 on 2026-04-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_seed_demo_farmer_profile_990011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmercodesequence',
            options={'ordering': ['year']},
        ),
    ]
