# Generated by Django 6.0.3 on 2026-04-21 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_farmercodesequence_options'),
        ('api', '0005_seed_demo_farmer_profile_990011'),
    ]

    operations = [
    ]
