# Generated by GPT-5.2 on 2026-04-27

from django.db import migrations, models
from django.utils import timezone


def _format_case_code(n: int, year: int) -> str:
    return f"CSE-{n:04d}-{year}"


def _format_record_code(n: int, year: int) -> str:
    return f"REC-{n:04d}-{year}"


def _try_parse_number_year(code: str):
    """
    Parse patterns:
      CSE-0001-2026
      REC-0001-2026
    """
    try:
        parts = str(code or "").split("-")
        if len(parts) != 3:
            return None
        n = int(parts[1])
        y = int(parts[2])
        return n, y
    except Exception:
        return None


def backfill_codes(apps, schema_editor):
    Case = apps.get_model("api", "Case")
    ScoutingReport = apps.get_model("api", "ScoutingReport")
    CaseCodeSequence = apps.get_model("api", "CaseCodeSequence")
    ScoutingRecordCodeSequence = apps.get_model("api", "ScoutingRecordCodeSequence")

    # Backfill cases oldest-first (stable).
    cases = list(Case.objects.all().order_by("date_submitted", "id"))
    counters_case: dict[int, int] = {}
    for c in cases:
        if getattr(c, "case_code", None):
            continue
        dt = getattr(c, "date_submitted", None)
        year = int(dt.year) if dt else int(timezone.now().year)
        counters_case[year] = counters_case.get(year, 0) + 1
        c.case_code = _format_case_code(counters_case[year], year)
        c.save(update_fields=["case_code"])

    # Backfill scouting records oldest-first (stable).
    recs = list(ScoutingReport.objects.all().order_by("submitted_at", "id"))
    counters_rec: dict[int, int] = {}
    for r in recs:
        if getattr(r, "record_code", None):
            continue
        dt = getattr(r, "submitted_at", None)
        year = int(dt.year) if dt else int(timezone.now().year)
        counters_rec[year] = counters_rec.get(year, 0) + 1
        r.record_code = _format_record_code(counters_rec[year], year)
        r.save(update_fields=["record_code"])

    # Ensure sequences are at least the highest issued number per year.
    for year, last in counters_case.items():
        obj, _ = CaseCodeSequence.objects.get_or_create(year=year)
        if obj.last_number < last:
            obj.last_number = last
            obj.save(update_fields=["last_number"])
    for year, last in counters_rec.items():
        obj, _ = ScoutingRecordCodeSequence.objects.get_or_create(year=year)
        if obj.last_number < last:
            obj.last_number = last
            obj.save(update_fields=["last_number"])

    # Also account for any pre-existing codes (if any) to prevent collisions.
    existing_case = (
        Case.objects.exclude(case_code__isnull=True)
        .exclude(case_code="")
        .values_list("case_code", flat=True)
    )
    parsed_case: dict[int, int] = {}
    for code in existing_case:
        parsed = _try_parse_number_year(code)
        if not parsed:
            continue
        n, y = parsed
        parsed_case[y] = max(parsed_case.get(y, 0), n)
    for y, n in parsed_case.items():
        obj, _ = CaseCodeSequence.objects.get_or_create(year=y)
        if obj.last_number < n:
            obj.last_number = n
            obj.save(update_fields=["last_number"])

    existing_rec = (
        ScoutingReport.objects.exclude(record_code__isnull=True)
        .exclude(record_code="")
        .values_list("record_code", flat=True)
    )
    parsed_rec: dict[int, int] = {}
    for code in existing_rec:
        parsed = _try_parse_number_year(code)
        if not parsed:
            continue
        n, y = parsed
        parsed_rec[y] = max(parsed_rec.get(y, 0), n)
    for y, n in parsed_rec.items():
        obj, _ = ScoutingRecordCodeSequence.objects.get_or_create(year=y)
        if obj.last_number < n:
            obj.last_number = n
            obj.save(update_fields=["last_number"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_farmercodesequence_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseCodeSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["year"]},
        ),
        migrations.AddField(
            model_name="case",
            name="case_code",
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="ScoutingRecordCodeSequence",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("year", models.PositiveIntegerField(unique=True)),
                ("last_number", models.PositiveIntegerField(default=0)),
            ],
            options={"ordering": ["year"]},
        ),
        migrations.AddField(
            model_name="scoutingreport",
            name="record_code",
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(backfill_codes, migrations.RunPython.noop),
    ]

