# Generated by Django 5.2.8 on 2026-03-25 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_fix_id_type'),
        ('admin', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql='''
                ALTER TABLE django_admin_log 
                ALTER COLUMN user_id TYPE uuid 
                USING user_id::text::uuid;
                
                ALTER TABLE django_admin_log 
                ADD CONSTRAINT django_admin_log_user_id_fk_accounts_user_id 
                FOREIGN KEY (user_id) REFERENCES accounts_user(id) 
                DEFERRABLE INITIALLY DEFERRED;
            ''',
            reverse_sql='''
                ALTER TABLE django_admin_log 
                DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fk_accounts_user_id;
                
                ALTER TABLE django_admin_log 
                ALTER COLUMN user_id TYPE bigint 
                USING user_id::text::bigint;
            '''
        ),
    ]
