# Generated by Django 5.2.8 on 2026-03-25 17:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_entity_user_county_user_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(default=list)),
            ],
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('Exporter', 'Exporter'), ('Government - KEPHIS', 'Government - KEPHIS'), ('Government - HCDA', 'Government - HCDA'), ('Partner Organization', 'Partner Organization')], max_length=20),
        ),
        migrations.RunSQL(
            sql='ALTER TABLE accounts_user DROP COLUMN role;',
            reverse_sql='ALTER TABLE accounts_user ADD COLUMN role varchar(20) NULL;',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.role'),
        ),
    ]
