# Generated by Django 5.2.8 on 2026-03-25 17:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_role_alter_entity_entity_type_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('view_cases', models.BooleanField(default=False)),
                ('create_cases', models.BooleanField(default=False)),
                ('edit_cases', models.BooleanField(default=False)),
                ('delete_cases', models.BooleanField(default=False)),
                ('view_reports', models.BooleanField(default=False)),
                ('create_reports', models.BooleanField(default=False)),
                ('manage_users', models.BooleanField(default=False)),
                ('manage_settings', models.BooleanField(default=False)),
                ('view_knowledge_base', models.BooleanField(default=False)),
                ('edit_knowledge_base', models.BooleanField(default=False)),
            ],
        ),
    ]
