# Generated by Django 5.2.8 on 2026-03-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_apppermission_role_permissions_delete_rolepermission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apppermission',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['role_name']},
        ),
    ]
