# Generated by Django 6.0.3 on 2026-05-12 09:09

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='HCDA_license',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='primary_county',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='county',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=accounts.models.user_profile_pic_path),
        ),
    ]
