# Generated by Django 6.0.3 on 2026-04-17 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_set_kephis_login_for_demo_account'),
        ('accounts', '0015_user_managed_by'),
    ]

    operations = [
    ]
