# Generated by Django 6.0.3 on 2026-04-08 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farmerName', models.CharField(max_length=255)),
                ('hcdaRegNumber', models.CharField(max_length=100, unique=True)),
                ('ward', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('acreage', models.FloatField()),
                ('globalGAPStatus', models.CharField(max_length=50)),
                ('globalGAPExpiry', models.DateField()),
                ('primaryExporter', models.CharField(max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Farmer Registration',
                'verbose_name_plural': 'Farmer Registrations',
            },
        ),
    ]
