# Generated by Django 6.0.3 on 2026-04-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcda_registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmerregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Farmer Registration', 'verbose_name_plural': 'Farmer Registrations'},
        ),
    ]
