# Generated by Django 6.0.3 on 2026-05-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcda_registry', '0002_alter_farmerregistration_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmerregistration',
            name='county',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='farmerregistration',
            name='hcdaRegNumber',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='farmerregistration',
            name='ward',
            field=models.CharField(max_length=500),
        ),
    ]
