# Generated by Django 6.0.3 on 2026-05-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
