# Generated by Django 5.2.8 on 2026-04-08 02:09

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuarantineManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blockId', models.CharField(max_length=50)),
                ('farmName', models.CharField(max_length=255)),
                ('county', models.CharField(max_length=100)),
                ('pestType', models.CharField(max_length=100)),
                ('captureRate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lastInspection', models.DateField()),
                ('kephisStatus', models.CharField(choices=[('gated', 'Gated'), ('pending', 'Pending'), ('cleared', 'Cleared')], default='pending', max_length=20)),
                ('inspector', models.CharField(max_length=255)),
                ('selected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Quarantine Management',
            },
        ),
    ]
