# Generated by Django 6.0.3 on 2026-05-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kephis_quarantine', '0002_alter_quarantinemanagement_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantinemanagement',
            name='county',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='quarantinemanagement',
            name='pestType',
            field=models.CharField(max_length=500),
        ),
    ]
