# Generated by Django 6.0.3 on 2026-04-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kephis_quarantine', '0007_china_export_approval_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chinafarmidsequence',
            options={'ordering': ['year']},
        ),
        migrations.RenameIndex(
            model_name='chinafarmcertification',
            new_name='kephis_quar_farmer__f19a95_idx',
            old_name='kephis_quar_farmer__3b6b09_idx',
        ),
        migrations.RenameIndex(
            model_name='chinafarmcertification',
            new_name='kephis_quar_status_063ecf_idx',
            old_name='kephis_quar_status__d51739_idx',
        ),
    ]
