# Generated by Django 5.2.8 on 2026-04-07 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentry',
            name='active_use_cases',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='approved_content',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='chemical_gate',
            field=models.CharField(choices=[('gated', 'Gated'), ('open', 'Open')], default='open', max_length=10),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='severity',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='knowledgeentry',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]

