# Generated by Django 6.0.3 on 2026-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_knowledgeentry_active_use_cases_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgeentry',
            name='regional_alerts',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
