# Generated by Django 6.0.3 on 2026-04-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0002_knowledgeentry_active_use_cases_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgeentry',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Knowledge Entries'},
        ),
    ]
