# Generated by Django 6.0.3 on 2026-05-10 19:21

import knowledge_base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0003_alter_knowledgeentry_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgeentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=knowledge_base.models.knowledge_image_path),
        ),
        migrations.AlterField(
            model_name='knowledgeentry',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to=knowledge_base.models.knowledge_source_path),
        ),
    ]
