# Generated by Django 5.2.8 on 2026-03-25 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_role_permissions_role_role_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='role_permissions',
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='role',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='accounts.role'),
        ),
    ]
