# Generated by Django 6.0.3 on 2026-04-14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_set_admin_login_for_0798208346'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='managed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='managed_farmers',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

