# Generated by Django 6.0.3 on 2026-04-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_hcda_remove_nav_farmers'),
        ('accounts', '0020_hcda_restrict_nav_permissions'),
        ('accounts', '0020_reseed_demo_accounts_if_missing'),
    ]

    operations = [
    ]
