# Generated by Django 5.2.8 on 2026-04-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
        ('pest_scouting', '0002_alter_weeklyrecord_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='pest_scouting_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='pest_scouting.weeklyrecord'),
        ),
    ]
