# Generated by Django 6.0.3 on 2026-04-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_case_pest_scouting_record'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='assigned_agronomist',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='case_management_assigned_cases',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

