# Generated by Django 6.0.3 on 2026-04-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_case_pest_scouting_record'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at']},
        ),
    ]
