# Generated by Django 6.0.3 on 2026-04-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_alter_case_assigned_agronomist_related_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recommended_actions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('verified', 'Verified'), ('closed', 'Closed')], default='new', max_length=20),
        ),
    ]
