# Generated by Django 6.0.3 on 2026-04-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_alter_case_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='application_rate',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='pre_harvest_interval',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recommended_actions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='recommended_chemical',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('Under Review', 'Under Review'), ('Advisory Issued', 'Advisory Issued'), ('Closed', 'Closed')], default='Under Review', max_length=20),
        ),
    ]
