# Generated by Django 6.0.3 on 2026-04-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0004_case_application_rate_case_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='initial_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
