# Generated by Django 6.0.3 on 2026-04-22 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0005_case_case_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='casecodesequence',
            options={'ordering': ['year']},
        ),
    ]
