# Generated by Django 6.0.3 on 2026-04-02 10:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_apppermission_options_alter_role_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('condition', models.CharField(max_length=64)),
                ('threshold', models.CharField(max_length=64)),
                ('county', models.CharField(blank=True, default='', max_length=128)),
                ('pest', models.CharField(blank=True, default='', max_length=255)),
                ('action', models.CharField(max_length=32)),
                ('recipients', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'active'), ('inactive', 'inactive')], default='active', max_length=16)),
                ('triggered_count', models.PositiveIntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('farm_name', models.CharField(blank=True, default='', max_length=255)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('county', models.CharField(blank=True, default='', max_length=128)),
                ('ward', models.CharField(blank=True, default='', max_length=128)),
                ('sub_county', models.CharField(blank=True, default='', max_length=128)),
                ('primary_channel', models.CharField(choices=[('smartphone', 'smartphone'), ('ussd', 'ussd')], default='smartphone', max_length=16)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('total_acres', models.FloatField(default=0)),
                ('blocks_managed', models.PositiveIntegerField(default=0)),
                ('trees_count', models.PositiveIntegerField(default=0)),
                ('export_eligibility', models.CharField(choices=[('ready', 'ready'), ('at-risk', 'at-risk'), ('suspended', 'suspended')], default='ready', max_length=16)),
                ('weekly_scouting_logs_4w', models.JSONField(default=list)),
                ('overdue_scouts', models.BooleanField(default=False)),
                ('last_inspection', models.CharField(blank=True, default='', max_length=64)),
                ('last_scouting_status', models.CharField(blank=True, default='no-pests', max_length=32)),
                ('last_scouting_finding', models.CharField(blank=True, default='', max_length=255)),
                ('last_scouting_date', models.CharField(blank=True, default='', max_length=64)),
                ('last_scouting_scout_name', models.CharField(blank=True, default='', max_length=255)),
                ('linked_exporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_farmers_profiles', to='accounts.entity')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FarmBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('acres', models.FloatField(default=0)),
                ('trees', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(blank=True, default='', max_length=64)),
                ('last_inspection', models.CharField(blank=True, default='', max_length=64)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.farmerprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('unknown', 'unknown')], default='unknown', max_length=16)),
                ('pest_disease', models.CharField(blank=True, default='', max_length=255)),
                ('pest_disease_kiswahili', models.CharField(blank=True, default='', max_length=255)),
                ('date_submitted', models.DateTimeField(blank=True, null=True)),
                ('submission_channel', models.CharField(blank=True, default='smartphone', max_length=32)),
                ('scout_name', models.CharField(blank=True, default='', max_length=255)),
                ('scout_phone', models.CharField(blank=True, default='', max_length=32)),
                ('affected_trees', models.PositiveIntegerField(default=0)),
                ('symptoms', models.JSONField(default=list)),
                ('symptom_codes', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='new', max_length=64)),
                ('assigned_agronomist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='api.farmblock')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='api.farmerprofile')),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.CreateModel(
            name='ScoutingReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('app', 'app'), ('ussd', 'ussd')], default='app', max_length=16)),
                ('severity', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], default='low', max_length=16)),
                ('finding', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('clean', 'clean'), ('detected', 'detected')], default='clean', max_length=16)),
                ('media_preview', models.URLField(blank=True, default='')),
                ('ussd_code', models.CharField(blank=True, default='', max_length=32)),
                ('scout_name', models.CharField(blank=True, default='', max_length=255)),
                ('reviewed', models.CharField(choices=[('new', 'new'), ('under-review', 'under-review'), ('reviewed', 'reviewed')], default='new', max_length=32)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_scouting_reports', to=settings.AUTH_USER_MODEL)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scouting_reports', to='api.farmblock')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scouting_reports', to='api.farmerprofile')),
                ('related_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_scouting_reports', to='api.case')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['-submitted_at'], name='api_scoutin_submitt_9d2533_idx'), models.Index(fields=['farmer', '-submitted_at'], name='api_scoutin_farmer__7a98f1_idx')],
            },
        ),
    ]
