# Generated by GPT-5.2 on 2026-05-07

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_case_case_code_and_scoutingreport_record_code"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0010_alter_apppermission_options_alter_role_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionVolumeSubmission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("county", models.CharField(blank=True, default="", max_length=128)),
                ("sub_county", models.CharField(blank=True, default="", max_length=128)),
                ("ward", models.CharField(blank=True, default="", max_length=128)),
                ("village", models.CharField(blank=True, default="", max_length=128)),
                ("tonnage_mt", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("regulator", "regulator"), ("exporter", "exporter"), ("cooperative", "cooperative")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "draft"), ("submitted", "submitted"), ("approved", "approved"), ("rejected", "rejected")],
                        default="submitted",
                        max_length=16,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_volume_submissions",
                        to="accounts.entity",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="production_volume_submissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-month", "-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productionvolumesubmission",
            index=models.Index(fields=["-year", "-month"], name="api_produ_year_6b0a7a_idx"),
        ),
        migrations.AddIndex(
            model_name="productionvolumesubmission",
            index=models.Index(fields=["county", "ward"], name="api_produ_county_1b2c02_idx"),
        ),
        migrations.AddIndex(
            model_name="productionvolumesubmission",
            index=models.Index(fields=["source_type"], name="api_produ_source__52e7cd_idx"),
        ),
        migrations.AddIndex(
            model_name="productionvolumesubmission",
            index=models.Index(fields=["status"], name="api_produ_status_0ef50c_idx"),
        ),
        migrations.CreateModel(
            name="BroadcastCampaign",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("county", models.CharField(blank=True, default="", max_length=128)),
                ("ward", models.CharField(blank=True, default="", max_length=128)),
                ("village", models.CharField(blank=True, default="", max_length=128)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[("queued", "queued"), ("sending", "sending"), ("completed", "completed"), ("failed", "failed")],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="BroadcastRecipient",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("phone_number", models.CharField(max_length=32)),
                ("status", models.CharField(blank=True, default="queued", max_length=16)),
                ("error", models.TextField(blank=True, default="")),
                ("provider_response", models.JSONField(blank=True, default=dict)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="recipients", to="api.broadcastcampaign"),
                ),
                (
                    "farmer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcast_deliveries",
                        to="api.farmerprofile",
                    ),
                ),
            ],
            options={"ordering": ["-sent_at", "-id"]},
        ),
        migrations.AddIndex(
            model_name="broadcastrecipient",
            index=models.Index(fields=["campaign", "status"], name="api_broadc_campai_1f3a9a_idx"),
        ),
        migrations.AddIndex(
            model_name="broadcastrecipient",
            index=models.Index(fields=["phone_number"], name="api_broadc_phone__8caa12_idx"),
        ),
    ]

