# Generated by Django 6.0.3 on 2026-05-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_market_intel_production_and_broadcast'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='broadcastrecipient',
            new_name='api_broadca_campaig_ea8a4f_idx',
            old_name='api_broadc_campai_1f3a9a_idx',
        ),
        migrations.RenameIndex(
            model_name='broadcastrecipient',
            new_name='api_broadca_phone_n_90fdbe_idx',
            old_name='api_broadc_phone__8caa12_idx',
        ),
        migrations.RenameIndex(
            model_name='productionvolumesubmission',
            new_name='api_product_year_8caaa0_idx',
            old_name='api_produ_year_6b0a7a_idx',
        ),
        migrations.RenameIndex(
            model_name='productionvolumesubmission',
            new_name='api_product_county_b52dbf_idx',
            old_name='api_produ_county_1b2c02_idx',
        ),
        migrations.RenameIndex(
            model_name='productionvolumesubmission',
            new_name='api_product_source__fb3212_idx',
            old_name='api_produ_source__52e7cd_idx',
        ),
        migrations.RenameIndex(
            model_name='productionvolumesubmission',
            new_name='api_product_status_19a0b4_idx',
            old_name='api_produ_status_0ef50c_idx',
        ),
    ]
