import type { ComplianceFarmerRow } from '../types';
export const PLACEHOLDER_COMPLIANCE_FARMERS: ComplianceFarmerRow[] = [
  {
    id: 'TRC-2024-001',
    name: 'Peter Mwangi',
    farmName: 'Kangema Avocado Growers',
    location: 'Kangema',
    county: 'Murang\'a',
    scoutingHistory: [true, true, true, true],
    riskLevel: 'high',
    submissionMode: 'app',
    reportStatus: 'pending-approval',
    lastUpdate: 'Mar 14, 2026',
    phoneNumber: '+254 722 345 678',
  },
  {
    id: 'TRC-2024-002',
    name: 'Grace Wanjiku',
    farmName: 'Gatanga Green Farms',
    location: 'Gatanga',
    county: 'Murang\'a',
    scoutingHistory: [true, true, false, true],
    riskLevel: 'medium',
    submissionMode: 'ussd',
    reportStatus: 'incomplete',
    lastUpdate: 'Mar 13, 2026',
    phoneNumber: '+254 733 456 789',
  },
  {
    id: 'TRC-2024-003',
    name: 'David Kipchirchir',
    farmName: 'Tigoni Avocado Estates',
    location: 'Tigoni',
    county: 'Kiambu',
    scoutingHistory: [true, true, true, true],
    riskLevel: 'low',
    submissionMode: 'app',
    reportStatus: 'export-ready',
    lastUpdate: 'Mar 13, 2026',
    phoneNumber: '+254 711 234 567',
  },
  {
    id: 'TRC-2024-004',
    name: 'Faith Njeri',
    farmName: 'Meru Sunrise Orchards',
    location: 'Meru Town',
    county: 'Meru',
    scoutingHistory: [true, true, true, true],
    riskLevel: 'low',
    submissionMode: 'app',
    reportStatus: 'export-ready',
    lastUpdate: 'Mar 12, 2026',
    phoneNumber: '+254 720 678 901',
  },
  {
    id: 'TRC-2024-005',
    name: 'John Kimani',
    farmName: 'Kiambu Highland Farms',
    location: 'Kiambu Town',
    county: 'Kiambu',
    scoutingHistory: [true, false, true, false],
    riskLevel: 'medium',
    submissionMode: 'ussd',
    reportStatus: 'incomplete',
    lastUpdate: 'Mar 12, 2026',
    phoneNumber: '+254 712 567 890',
  },
  {
    id: 'TRC-2024-006',
    name: 'Mary Wambui',
    farmName: 'Nyeri Valley Growers',
    location: 'Nyeri Town',
    county: 'Nyeri',
    scoutingHistory: [true, true, true, true],
    riskLevel: 'low',
    submissionMode: 'app',
    reportStatus: 'export-ready',
    lastUpdate: 'Mar 11, 2026',
    phoneNumber: '+254 734 678 901',
  },
  {
    id: 'TRC-2024-007',
    name: 'Samuel Omondi',
    farmName: 'Bungoma Green Valley',
    location: 'Bungoma',
    county: 'Bungoma',
    scoutingHistory: [false, false, false, true],
    riskLevel: 'high',
    submissionMode: 'ussd',
    reportStatus: 'incomplete',
    lastUpdate: 'Mar 8, 2026',
    phoneNumber: '+254 745 123 456',
  },
  {
    id: 'TRC-2024-008',
    name: 'Jane Wambui',
    farmName: 'Limuru Avocado Hub',
    location: 'Limuru',
    county: 'Kiambu',
    scoutingHistory: [true, true, true, false],
    riskLevel: 'low',
    submissionMode: 'app',
    reportStatus: 'pending-approval',
    lastUpdate: 'Mar 10, 2026',
    phoneNumber: '+254 723 987 654',
  },
  {
    id: 'TRC-2024-009',
    name: 'Joseph Kariuki',
    farmName: 'Thika Green Farms',
    location: 'Thika',
    county: 'Kiambu',
    scoutingHistory: [true, true, true, true],
    riskLevel: 'medium',
    submissionMode: 'app',
    reportStatus: 'export-ready',
    lastUpdate: 'Mar 14, 2026',
    phoneNumber: '+254 715 234 567',
  },
  {
    id: 'TRC-2024-010',
    name: 'Lucy Wanjiru',
    farmName: 'Embu Highland Estates',
    location: 'Embu',
    county: 'Embu',
    scoutingHistory: [true, true, false, false],
    riskLevel: 'high',
    submissionMode: 'ussd',
    reportStatus: 'incomplete',
    lastUpdate: 'Mar 9, 2026',
    phoneNumber: '+254 728 456 789',
  },
];
