import type { DashboardPayload } from '../types';

export const PLACEHOLDER_DASHBOARD: DashboardPayload = {
  metrics: [
    {
      label: 'Total Cases',
      value: 415,
      trendUp: true,
      trendPercent: 12,
      trendVs: 'vs last month',
      icon: 'activity',
      iconBg: '#74C69D20',
      iconColor: '#2D6A4F',
    },
    {
      label: 'Active Outbreaks',
      value: 23,
      trendUp: false,
      trendPercent: 8,
      trendVs: 'vs last month',
      icon: 'alert',
      iconBg: '#FEE2E2',
      iconColor: '#DC2626',
    },
    {
      label: 'Scouting Compliance',
      value: '95%',
      trendUp: true,
      trendPercent: 2,
      trendVs: 'vs last week',
      icon: 'check',
      iconBg: '#74C69D20',
      iconColor: '#74C69D',
    },
    {
      label: 'Pending Reviews',
      value: 12,
      sublabel: 'Avg. wait: 6.2 hrs',
      icon: 'clock',
      iconBg: '#FEF3C7',
      iconColor: '#D97706',
    },
    {
      label: 'Trap checks (30d)',
      value: 0,
      icon: 'target',
      iconBg: '#E0F2FE',
      iconColor: '#0369A1',
      sublabel: 'Mobile trap log',
    },
  ],
  complianceSummary: { target: 95, current: 95 },
  todayLabel: 'Mar 15, 2026',
  todayDateKey: '2026-03-15',
  recentTrapActivity: [],
  weeklyComplianceData: [
    { week: 'Week 1', compliance: 92, target: 95 },
    { week: 'Week 2', compliance: 88, target: 95 },
    { week: 'Week 3', compliance: 94, target: 95 },
    { week: 'Week 4', compliance: 91, target: 95 },
    { week: 'Week 5', compliance: 96, target: 95 },
    { week: 'Week 6', compliance: 89, target: 95 },
    { week: 'Week 7', compliance: 93, target: 95 },
    { week: 'Week 8', compliance: 95, target: 95 },
  ],
  weeklyTrends: [
    { week: 'Week 1', cases: 12, resolved: 8, fieldReports: 24 },
    { week: 'Week 2', cases: 15, resolved: 11, fieldReports: 30 },
    { week: 'Week 3', cases: 18, resolved: 14, fieldReports: 28 },
    { week: 'Week 4', cases: 22, resolved: 16, fieldReports: 35 },
    { week: 'Week 5', cases: 19, resolved: 18, fieldReports: 31 },
    { week: 'Week 6', cases: 25, resolved: 20, fieldReports: 40 },
    { week: 'Week 7', cases: 28, resolved: 22, fieldReports: 38 },
    { week: 'Week 8', cases: 24, resolved: 21, fieldReports: 36 },
  ],
  pestDistribution: [
    { name: 'Avocado Thrips', value: 145, color: '#DC2626' },
    { name: 'Phytophthora Root Rot', value: 98, color: '#D97706' },
    { name: 'Persea Mite', value: 76, color: '#2D6A4F' },
    { name: 'Anthracnose', value: 54, color: '#74C69D' },
    { name: 'Other', value: 42, color: '#E0DDD6' },
  ],
  triageQueue: [
    {
      id: 'CSE-1024',
      farm: 'Kangema Avocado Growers',
      location: "Murang'a County",
      severity: 'high',
      pest: 'Avocado Thrips',
      scout: 'Jane Wambui',
      submittedHours: 2,
      priority: 1,
    },
    {
      id: 'CSE-1020',
      farm: 'Kiambu Highland Farms',
      location: 'Kiambu County',
      severity: 'high',
      pest: 'Anthracnose',
      scout: 'Grace Achieng',
      submittedHours: 4,
      priority: 2,
    },
    {
      id: 'CSE-1023',
      farm: 'Gatanga Green Farms',
      location: "Murang'a County",
      severity: 'high',
      pest: 'Root Rot',
      scout: 'Samuel Omondi',
      submittedHours: 8,
      priority: 3,
    },
    {
      id: 'CSE-1022',
      farm: 'Tigoni Avocado Estates',
      location: 'Kiambu County',
      severity: 'medium',
      pest: 'Persea Mite',
      scout: 'Mary Akinyi',
      submittedHours: 12,
      priority: 4,
    },
  ],
  recentScoutingRecords: [
    {
      id: 'SCT-2045',
      source: 'registry',
      recordCode: 'REC-2045-2026',
      scout: 'Jane Wambui',
      farm: 'Kangema Avocado Growers',
      location: "Murang'a County",
      date: '2026-03-15',
      time: '14:30',
      blocksInspected: 3,
      issuesFound: 2,
      status: 'detected',
      blockName: 'Block A',
      trapSummary: '',
      findingSummary: 'Thrips pressure elevated',
    },
    {
      id: 'SCT-2044',
      source: 'registry',
      recordCode: 'REC-2044-2026',
      scout: 'Peter Mwangi',
      farm: 'Nyeri Valley Growers',
      location: 'Nyeri County',
      date: '2026-03-15',
      time: '12:15',
      blocksInspected: 2,
      issuesFound: 0,
      status: 'clean',
      blockName: 'North ridge',
      findingSummary: 'No issues',
    },
    {
      id: 'SCT-2043',
      source: 'registry',
      recordCode: 'REC-2043-2026',
      scout: 'Grace Achieng',
      farm: 'Kiambu Highland Farms',
      location: 'Kiambu County',
      date: '2026-03-15',
      time: '10:45',
      blocksInspected: 4,
      issuesFound: 3,
      status: 'detected',
      blockName: 'Block C',
      findingSummary: 'Anthracnose on fruit',
    },
    {
      id: 'SCT-2042',
      source: 'registry',
      recordCode: 'REC-2042-2026',
      scout: 'Samuel Omondi',
      farm: 'Gatanga Green Farms',
      location: "Murang'a County",
      date: '2026-03-15',
      time: '09:20',
      blocksInspected: 2,
      issuesFound: 1,
      status: 'detected',
      blockName: 'Lower plot',
      findingSummary: 'Mite activity',
    },
    {
      id: 'SCT-2041',
      source: 'registry',
      recordCode: 'REC-2041-2026',
      scout: 'Mary Akinyi',
      farm: 'Tigoni Avocado Estates',
      location: 'Kiambu County',
      date: '2026-03-14',
      time: '16:00',
      blocksInspected: 5,
      issuesFound: 2,
      status: 'detected',
      blockName: 'Hass 1',
      findingSummary: 'Leaf spot',
    },
    {
      id: 'app-weekly-demo-1',
      source: 'mobile_app',
      recordCode: 'APP-DEMO',
      scout: 'Demo Farmer',
      farm: 'Tigoni Avocado Estates',
      location: 'Kiambu County',
      date: '2026-03-14',
      time: '08:00',
      blocksInspected: 1,
      issuesFound: 1,
      status: 'detected',
      blockName: 'Block A',
      variety: 'Hass',
      trapSummary: 'Yellow sticky (×4, avg 2)',
      pestSummary: 'False codling moth (3/trap)',
      diseaseSummary: 'Anthracnose',
      mobileBlockLine: 'Kiambu / Block A / 120 trees',
      farmNameAsSubmitted: 'Green Valley Demo Farm',
      submissionLocation: 'Ward 3, Kiambu',
      beneficialSummary: 'Lady beetles, lacewings',
      diseaseMetaSummary: 'Fruit · flowering · visual',
      gpsSummary: '-1.234567, 36.789012',
      findingSummary: 'Elevated pest pressure; disease on fruit',
    },
  ],
};
