import type { DashboardPayload } from '../types';

export const PLACEHOLDER_DASHBOARD: DashboardPayload = {
  metrics: [
    {
      label: 'Total Cases',
      value: 415,
      trendUp: true,
      trendPercent: 12,
      trendVs: 'vs last month',
      icon: 'activity',
      iconBg: '#74C69D20',
      iconColor: '#2D6A4F',
    },
    {
      label: 'Active Outbreaks',
      value: 23,
      trendUp: false,
      trendPercent: 8,
      trendVs: 'vs last month',
      icon: 'alert',
      iconBg: '#FEE2E2',
      iconColor: '#DC2626',
    },
    {
      label: 'Scouting Compliance',
      value: '95%',
      trendUp: true,
      trendPercent: 2,
      trendVs: 'vs last week',
      icon: 'check',
      iconBg: '#74C69D20',
      iconColor: '#74C69D',
    },
    {
      label: 'Pending Reviews',
      value: 12,
      sublabel: 'Avg. wait: 6.2 hrs',
      icon: 'clock',
      iconBg: '#FEF3C7',
      iconColor: '#D97706',
    },
  ],
  complianceSummary: { target: 95, current: 95 },
  todayLabel: 'Mar 15, 2026',
  weeklyComplianceData: [
    { week: 'Week 1', compliance: 92, target: 95 },
    { week: 'Week 2', compliance: 88, target: 95 },
    { week: 'Week 3', compliance: 94, target: 95 },
    { week: 'Week 4', compliance: 91, target: 95 },
    { week: 'Week 5', compliance: 96, target: 95 },
    { week: 'Week 6', compliance: 89, target: 95 },
    { week: 'Week 7', compliance: 93, target: 95 },
    { week: 'Week 8', compliance: 95, target: 95 },
  ],
  weeklyTrends: [
    { week: 'Week 1', cases: 12, resolved: 8 },
    { week: 'Week 2', cases: 15, resolved: 11 },
    { week: 'Week 3', cases: 18, resolved: 14 },
    { week: 'Week 4', cases: 22, resolved: 16 },
    { week: 'Week 5', cases: 19, resolved: 18 },
    { week: 'Week 6', cases: 25, resolved: 20 },
    { week: 'Week 7', cases: 28, resolved: 22 },
    { week: 'Week 8', cases: 24, resolved: 21 },
  ],
  pestDistribution: [
    { name: 'Avocado Thrips', value: 145, color: '#DC2626' },
    { name: 'Phytophthora Root Rot', value: 98, color: '#D97706' },
    { name: 'Persea Mite', value: 76, color: '#2D6A4F' },
    { name: 'Anthracnose', value: 54, color: '#74C69D' },
    { name: 'Other', value: 42, color: '#E0DDD6' },
  ],
  triageQueue: [
    {
      id: 'CSE-1024',
      farm: 'Kangema Avocado Growers',
      location: "Murang'a County",
      severity: 'high',
      pest: 'Avocado Thrips',
      scout: 'Jane Wambui',
      submittedHours: 2,
      priority: 1,
    },
    {
      id: 'CSE-1020',
      farm: 'Kiambu Highland Farms',
      location: 'Kiambu County',
      severity: 'high',
      pest: 'Anthracnose',
      scout: 'Grace Achieng',
      submittedHours: 4,
      priority: 2,
    },
    {
      id: 'CSE-1023',
      farm: 'Gatanga Green Farms',
      location: "Murang'a County",
      severity: 'high',
      pest: 'Root Rot',
      scout: 'Samuel Omondi',
      submittedHours: 8,
      priority: 3,
    },
    {
      id: 'CSE-1022',
      farm: 'Tigoni Avocado Estates',
      location: 'Kiambu County',
      severity: 'medium',
      pest: 'Persea Mite',
      scout: 'Mary Akinyi',
      submittedHours: 12,
      priority: 4,
    },
  ],
  recentScoutingRecords: [
    {
      id: 'SCT-2045',
      scout: 'Jane Wambui',
      farm: 'Kangema Avocado Growers',
      location: "Murang'a County",
      date: 'Mar 15, 2026',
      time: '14:30',
      blocksInspected: 3,
      issuesFound: 2,
      status: 'completed',
    },
    {
      id: 'SCT-2044',
      scout: 'Peter Mwangi',
      farm: 'Nyeri Valley Growers',
      location: 'Nyeri County',
      date: 'Mar 15, 2026',
      time: '12:15',
      blocksInspected: 2,
      issuesFound: 0,
      status: 'completed',
    },
    {
      id: 'SCT-2043',
      scout: 'Grace Achieng',
      farm: 'Kiambu Highland Farms',
      location: 'Kiambu County',
      date: 'Mar 15, 2026',
      time: '10:45',
      blocksInspected: 4,
      issuesFound: 3,
      status: 'completed',
    },
    {
      id: 'SCT-2042',
      scout: 'Samuel Omondi',
      farm: 'Gatanga Green Farms',
      location: "Murang'a County",
      date: 'Mar 15, 2026',
      time: '09:20',
      blocksInspected: 2,
      issuesFound: 1,
      status: 'completed',
    },
    {
      id: 'SCT-2041',
      scout: 'Mary Akinyi',
      farm: 'Tigoni Avocado Estates',
      location: 'Kiambu County',
      date: 'Mar 14, 2026',
      time: '16:00',
      blocksInspected: 5,
      issuesFound: 2,
      status: 'completed',
    },
  ],
};
