# Generated by Django 5.2.8 on 2026-04-07 08:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=255)),
                ('number_of_trees', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_blocks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variety', models.CharField(max_length=100)),
                ('type_of_trap', models.CharField(max_length=100)),
                ('number_of_trap', models.PositiveIntegerField()),
                ('traps_replaced', models.PositiveIntegerField()),
                ('any_pests_observed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('pests_observed', models.CharField(blank=True, choices=[('🦟 Mango fruit fly', '🦟 Mango fruit fly'), (' Mediterranean fruit fly', '🦟 Mediterranean fruit fly'), ('🦟 Natal fruit fly', '🦟 Natal fruit fly'), ('🐛 False codling moth', '🐛 False codling moth'), ('🦗 Thrips', '🦗 Thrips'), ('🐛 Caterpillars', '🐛 Caterpillars'), ('🕷 Persea mites', '🕷 Persea mites'), ('🪲 Fig wax scale', '🪲 Fig wax scale'), ('🪲 Red wax scale', '🪲 Red wax scale'), ('🦟 Melon fly', '🦟 Melon fly'), ('🐛 Whitefly', '🐛 Whitefly'), ('🦟 Oriental fruit fly', '🦟 Oriental fruit fly'), ('🐛 Broad mite', '🐛 Broad mite'), ('🪲 Shot-hole borer', '🪲 Shot-hole borer')], max_length=255, null=True)),
                ('beneficial_insects_observed', models.CharField(blank=True, choices=[('🐝 Bees', '🐝 Bees'), ('🐞 Ladybirds', '🐞 Ladybirds'), ('🪰 Lacewings', '🪰 Lacewings'), ('🕷️ Predatory mites', '🕷️ Predatory mites')], max_length=255, null=True)),
                ('number_of_trees_affected', models.PositiveIntegerField()),
                ('pest_plant_part_affected', models.CharField(blank=True, choices=[('🍃 Leaves', '🍃 Leaves'), ('🌸 Flowers', '🌸 Flowers'), ('🥑Fruits', '🥑Fruits'), ('🌿 Branches', '🌿 Branches'), ('🌱 Roots', '🌱 Roots'), ('❓ Other', '❓ Other')], max_length=100, null=True)),
                ('pest_crop_stage', models.CharField(blank=True, choices=[('🌸 Flowering', '🌸 Flowering'), ('🟢 Pin head', '🟢 Pin head'), ('⛳ Golf size', '⛳ Golf size'), ('🟡 Maturing', '🟡 Maturing'), ('🥑 Mature', '🥑 Mature')], max_length=100, null=True)),
                ('pest_detection_method', models.CharField(blank=True, choices=[('👁 Self-observation', '👁 Self-observation'), ('👷 Extension officer', '👷 Extension officer'), ('🏢 Agronomist', '🏢 Agronomist'), ('🔬 KEPHIS inspector', '🔬 KEPHIS inspector')], max_length=100, null=True)),
                ('pests_per_trap', models.DecimalField(decimal_places=2, max_digits=10)),
                ('any_diseases_observed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('disease', models.CharField(blank=True, choices=[('🟤 Anthracnose', '🟤 Anthracnose'), ('⚫ Black spot', '⚫ Black spot'), ('🌊 Phytophthora root rot', '🌊 Phytophthora root rot'), ('🍄 Armillaria root rot', '🍄 Armillaria root rot'), ('🦠 Sunblotch viroid', '🦠 Sunblotch viroid'), ('🟡 Cercospora spot', '🟡 Cercospora spot'), ('🔴 Stem end rot', '🔴 Stem end rot'), ('🟫 Avocado scab', '🟫 Avocado scab'), ('🦠 Bacterial canker', '🦠 Bacterial canker'), ('🍂 Fruit rot', '🍂 Fruit rot'), ('🌿 Weeds', '🌿 Weeds'), ('⚡ Nutrient deficiency', '⚡ Nutrient deficiency'), ('❄️ Frost damage', '❄️ Frost damage')], max_length=255, null=True)),
                ('disease_plant_part', models.CharField(blank=True, choices=[('🍃 Leaves', '🍃 Leaves'), ('🌸 Flowers', '🌸 Flowers'), ('🥑Fruits', '🥑Fruits'), ('🌿 Branches', '🌿 Branches'), ('🌱 Roots', '🌱 Roots'), ('❓ Other', '❓ Other')], max_length=100, null=True)),
                ('disease_crop_stage', models.CharField(blank=True, choices=[('🌸 Flowering', '🌸 Flowering'), ('🟢 Pin head', '🟢 Pin head'), ('⛳ Golf size', '⛳ Golf size'), ('🟡 Maturing', '🟡 Maturing'), ('🥑 Mature', '🥑 Mature')], max_length=100, null=True)),
                ('disease_detection_method', models.CharField(blank=True, choices=[('👁 Self-observation', '👁 Self-observation'), ('👷 Extension officer', '👷 Extension officer'), ('🏢 Agronomist', '🏢 Agronomist'), ('🔬 KEPHIS inspector', '🔬 KEPHIS inspector')], max_length=100, null=True)),
                ('number_of_photos_taken', models.PositiveIntegerField(default=0)),
                ('voice_note', models.FileField(blank=True, null=True, upload_to='voice_notes/')),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('actions_taken', models.CharField(choices=[('🌿 Farm sanitation', '🌿 Farm sanitation'), ('✂️ Pruning', '✂️ Pruning'), ('🪤 Traps installed', '🪤 Traps installed'), ('🔧 Traps serviced', '🔧 Traps serviced'), ('💊 Chemical control', '💊 Chemical control'), ('🐞 Biological control', '🐞 Biological control'), ('❌ No action taken', '❌ No action taken')], max_length=100)),
                ('outcome', models.CharField(choices=[('✅ Controlled', '✅ Controlled'), ('📉 Reduced', '📉 Reduced'), ('⚠️ Still present', '⚠️ Still present'), ('🔄 Follow-up needed', '🔄 Follow-up needed')], max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=15, max_digits=18, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_records', to='pest_scouting.farmblock')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

