# Generated by Django 6.0.3 on 2026-04-09 11:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0002_alter_weeklyrecord_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyrecord',
            name='actions_taken',
            field=models.CharField(choices=[('Farm sanitation', '🌿 Farm sanitation'), ('Pruning', '✂️ Pruning'), ('Traps installed', '🪤 Traps installed'), ('Traps serviced', '🔧 Traps serviced'), ('Chemical control', '💊 Chemical control'), ('Biological control', '🐞 Biological control'), ('No action taken', '❌ No action taken')], max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='beneficial_insects_observed',
            field=models.CharField(blank=True, choices=[('Bees', '🐝 Bees'), ('Ladybirds', '🐞 Ladybirds'), ('Lacewings', '🪰 Lacewings'), ('Predatory mites', '🕷️ Predatory mites')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='disease',
            field=models.CharField(blank=True, choices=[('Anthracnose', '🟤 Anthracnose'), ('Black spot', '⚫ Black spot'), ('Phytophthora root rot', '🌊 Phytophthora root rot'), ('Armillaria root rot', '🍄 Armillaria root rot'), ('Sunblotch viroid', '🦠 Sunblotch viroid'), ('Cercospora spot', '🟡 Cercospora spot'), ('Stem end rot', '🔴 Stem end rot'), ('Avocado scab', '🟫 Avocado scab'), ('Bacterial canker', '🦠 Bacterial canker'), ('Fruit rot', '🍂 Fruit rot'), ('Weeds', '🌿 Weeds'), ('Nutrient deficiency', '⚡ Nutrient deficiency'), ('Frost damage', '❄️ Frost damage')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='disease_crop_stage',
            field=models.CharField(blank=True, choices=[('Flowering', '🌸 Flowering'), ('Pin head', '🟢 Pin head'), ('Golf size', '⛳ Golf size'), ('Maturing', '🟡 Maturing'), ('Mature', '🥑 Mature')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='disease_detection_method',
            field=models.CharField(blank=True, choices=[('Self-observation', '👁 Self-observation'), ('Extension officer', '👷 Extension officer'), ('Agronomist', '🏢 Agronomist'), ('KEPHIS inspector', '🔬 KEPHIS inspector')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='disease_plant_part',
            field=models.CharField(blank=True, choices=[('Leaves', '🍃 Leaves'), ('Flowers', '🌸 Flowers'), ('Fruits', '🥑Fruits'), ('Branches', '🌿 Branches'), ('Roots', '🌱 Roots'), ('Other', '❓ Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='outcome',
            field=models.CharField(choices=[('Controlled', '✅ Controlled'), ('Reduced', '📉 Reduced'), ('Still present', '⚠️ Still present'), ('Follow-up needed', '🔄 Follow-up needed')], max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='pest_crop_stage',
            field=models.CharField(blank=True, choices=[('Flowering', '🌸 Flowering'), ('Pin head', '🟢 Pin head'), ('Golf size', '⛳ Golf size'), ('Maturing', '🟡 Maturing'), ('Mature', '🥑 Mature')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='pest_detection_method',
            field=models.CharField(blank=True, choices=[('Self-observation', '👁 Self-observation'), ('Extension officer', '👷 Extension officer'), ('Agronomist', '🏢 Agronomist'), ('KEPHIS inspector', '🔬 KEPHIS inspector')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='pest_plant_part_affected',
            field=models.CharField(blank=True, choices=[('Leaves', '🍃 Leaves'), ('Flowers', '🌸 Flowers'), ('Fruits', '🥑Fruits'), ('Branches', '🌿 Branches'), ('Roots', '🌱 Roots'), ('Other', '❓ Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='pests_observed',
            field=models.CharField(blank=True, choices=[('Mango fruit fly', '🦟 Mango fruit fly'), ('Mediterranean fruit fly', '🦟 Mediterranean fruit fly'), ('Natal fruit fly', '🦟 Natal fruit fly'), ('False codling moth', '🐛 False codling moth'), ('Thrips', '🦗 Thrips'), ('Caterpillars', '🐛 Caterpillars'), ('Persea mites', '🕷 Persea mites'), ('Fig wax scale', '🪲 Fig wax scale'), ('Red wax scale', '🪲 Red wax scale'), ('Melon fly', '🦟 Melon fly'), ('Whitefly', '🐛 Whitefly'), ('Oriental fruit fly', '🦟 Oriental fruit fly'), ('Broad mite', '🐛 Broad mite'), ('Shot-hole borer', '🪲 Shot-hole borer')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('farm_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('number_of_blocks', models.PositiveIntegerField(default=0)),
                ('total_trees', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farmer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='farmblock',
            name='farm_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='pest_scouting.farm'),
        ),
    ]
