# Generated by Django 6.0.3 on 2026-04-26 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0004_farmblock_boundary_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_type', models.CharField(choices=[('🐛 Pest', '🐛 Pest'), ('🍂 Disease', '🍂 Disease'), ('💧 Water Issue', '💧 Water Issue'), ('🌡️ Weather', '🌡️ Weather'), ('🦅 Animal/Bird', '🦅 Animal/Bird'), ('❓Other', '❓Other')], max_length=50)),
                ('urgency', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Urgent!', 'Urgent!')], max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='problem_reports/')),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trap',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trap_name', models.CharField(max_length=255)),
                ('number_of_traps', models.PositiveIntegerField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='traps/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_pest_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_pest_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dont_know/pest/photos/'),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_pest_voice',
            field=models.FileField(blank=True, null=True, upload_to='dont_know/pest/voice/'),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_trap_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_trap_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dont_know/trap/photos/'),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_trap_voice',
            field=models.FileField(blank=True, null=True, upload_to='dont_know/trap/voice/'),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_variety_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_variety_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dont_know/variety/photos/'),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_variety_voice',
            field=models.FileField(blank=True, null=True, upload_to='dont_know/variety/voice/'),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='overall_image',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_records/overall/'),
        ),
    ]
