# Generated by Django 6.0.3 on 2026-04-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0005_problemreport_trap_weeklyrecord_dont_know_pest_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_pest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_trap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_variety',
            field=models.BooleanField(default=False),
        ),
    ]
