# Generated by Django 6.0.3 on 2026-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0006_weeklyrecord_dont_know_pest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyrecord',
            name='actions_taken',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='outcome',
            field=models.CharField(max_length=100),
        ),
    ]
