# Generated by Django 6.0.3 on 2026-04-28 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0007_alter_weeklyrecord_actions_taken_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='farmblock',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='problemreport',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='trap',
            options={'ordering': ['-timestamp']},
        ),
    ]
