# Generated by Django 6.0.3 on 2026-04-28 19:38

from django.db import migrations, models
import json

def convert_to_json(apps, schema_editor):
    WeeklyRecord = apps.get_model('pest_scouting', 'WeeklyRecord')
    fields = [
        'actions_taken',
        'beneficial_insects_observed',
        'disease',
        'disease_plant_part',
        'pest_plant_part_affected',
        'pests_observed'
    ]
    for record in WeeklyRecord.objects.all():
        updated = False
        for field in fields:
            val = getattr(record, field)
            if val is not None:
                # If it's already a list or dict, it's already JSON-like (Django handles it)
                if isinstance(val, (list, dict)):
                    continue
                
                # If it's a string, check if it's already JSON
                if isinstance(val, str):
                    val_stripped = val.strip()
                    
                    # Handle empty string - should be an empty list for JSONField
                    if not val_stripped:
                        setattr(record, field, json.dumps([]))
                        updated = True
                        continue

                    if (val_stripped.startswith('[') and val_stripped.endswith(']')) or \
                       (val_stripped.startswith('{') and val_stripped.endswith('}')):
                        try:
                            json.loads(val_stripped)
                            continue # Already valid JSON
                        except json.JSONDecodeError:
                            pass
                    
                    # Not valid JSON string, or doesn't look like JSON, wrap it in a list and JSON dump it
                    setattr(record, field, json.dumps([val]))
                    updated = True
        if updated:
            record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0008_alter_farm_options_alter_farmblock_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='dont_know_pest_note',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='dont_know_pest_voice',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='dont_know_trap_note',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='dont_know_trap_voice',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='number_of_photos_taken',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='traps_replaced',
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='average_no_of_pest_per_trap',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='other_production_challenges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='trap_use',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.RunPython(convert_to_json, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='actions_taken',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='beneficial_insects_observed',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='disease',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='disease_plant_part',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='pest_plant_part_affected',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='pests_observed',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
