# Generated by Django 6.0.3 on 2026-04-28 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0009_remove_weeklyrecord_dont_know_pest_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='average_no_of_pest_per_trap',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='number_of_trap',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='pests_per_trap',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='type_of_trap',
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_beneficial_insects_observed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_beneficial_insects_observed_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_beneficial_insects_observed_photo',
            field=models.ImageField(blank=True, null=True, upload_to='dont_know/beneficial_insects/photos/'),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_disease',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_disease_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='dont_know_pest_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
