# Generated by Django 6.0.3 on 2026-04-28 21:39

from django.db import migrations, models


import json

def convert_to_json(apps, schema_editor):
    WeeklyRecord = apps.get_model('pest_scouting', 'WeeklyRecord')
    for record in WeeklyRecord.objects.all():
        val = record.other_production_challenges
        if val is not None:
            # If it's already a list or dict, skip
            if isinstance(val, (list, dict)):
                continue
            
            if isinstance(val, str):
                val_stripped = val.strip()
                if not val_stripped:
                    record.other_production_challenges = json.dumps([])
                    record.save()
                    continue
                
                # Try to parse as JSON
                if (val_stripped.startswith('[') and val_stripped.endswith(']')) or \
                   (val_stripped.startswith('{') and val_stripped.endswith('}')):
                    try:
                        json.loads(val_stripped)
                        continue # Already valid JSON
                    except json.JSONDecodeError:
                        pass
                
                # Not valid JSON string, wrap in list and dump to JSON string
                record.other_production_challenges = json.dumps([val])
                record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0010_remove_weeklyrecord_average_no_of_pest_per_trap_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_to_json, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='other_production_challenges',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
