# Generated by Django 6.0.3 on 2026-04-28 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0011_other_production_challenges_to_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyrecord',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
