# Generated by Django 6.0.3 on 2026-04-30 00:46

from django.db import migrations


def rename_pest_trap_key(apps, schema_editor):
    WeeklyRecord = apps.get_model('pest_scouting', 'WeeklyRecord')
    for record in WeeklyRecord.objects.all():
        if record.trap_use and isinstance(record.trap_use, list):
            updated = False
            for trap in record.trap_use:
                if isinstance(trap, dict):
                    if 'average_no_of_pest_per_trap' in trap:
                        trap['total_no_of_pests'] = trap.pop('average_no_of_pest_per_trap')
                        updated = True
                    if 'pests_per_trap' in trap:
                        # If both exist, we might have a conflict, but usually they are the same or only one exists
                        if 'total_no_of_pests' not in trap:
                            trap['total_no_of_pests'] = trap.pop('pests_per_trap')
                        else:
                            trap.pop('pests_per_trap')
                        updated = True
            if updated:
                record.save()

def reverse_rename_pest_trap_key(apps, schema_editor):
    WeeklyRecord = apps.get_model('pest_scouting', 'WeeklyRecord')
    for record in WeeklyRecord.objects.all():
        if record.trap_use and isinstance(record.trap_use, list):
            updated = False
            for trap in record.trap_use:
                if isinstance(trap, dict) and 'total_no_of_pests' in trap:
                    trap['average_no_of_pest_per_trap'] = trap.pop('total_no_of_pests')
                    updated = True
            if updated:
                record.save()

class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0012_alter_weeklyrecord_gps_latitude_and_more'),
    ]

    operations = [
        migrations.RunPython(rename_pest_trap_key, reverse_rename_pest_trap_key),
    ]
