# Generated by Django 6.0.3 on 2026-04-30 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0013_rename_pest_trap_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='number_of_trees_affected',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='pest_crop_stage',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='pest_detection_method',
        ),
        migrations.RemoveField(
            model_name='weeklyrecord',
            name='pest_plant_part_affected',
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='other_trap_photo',
            field=models.ImageField(blank=True, null=True, upload_to='weekly_records/traps/'),
        ),
    ]
