# Generated by Django 6.0.3 on 2026-04-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0014_remove_weeklyrecord_number_of_trees_affected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrecord',
            name='review_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklyrecord',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
