# Generated by Django 6.0.3 on 2026-04-30 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0015_weeklyrecord_review_notes_weeklyrecord_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyrecord',
            name='status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
