# Generated by Django 6.0.3 on 2026-05-05 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0016_weeklyrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreport',
            name='problem_type',
            field=models.CharField(choices=[('Pest', 'Pest'), ('Disease', 'Disease'), ('Water Issue', 'Water Issue'), ('Weather', 'Weather'), ('Animal/Bird', 'Animal/Bird'), ('Other', 'Other')], max_length=50),
        ),
    ]
