# Generated by Django 6.0.3 on 2026-05-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0017_alter_problemreport_problem_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farm',
            old_name='total_trees',
            new_name='farm_size',
        ),
    ]
