# Generated by Django 6.0.3 on 2026-05-10 19:21

import pest_scouting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0018_rename_total_trees_farm_farm_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pest_scouting.models.problem_report_photo_path),
        ),
        migrations.AlterField(
            model_name='trap',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=pest_scouting.models.trap_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='dont_know_beneficial_insects_observed_photo',
            field=models.ImageField(blank=True, null=True, upload_to=pest_scouting.models.dont_know_beneficial_insects_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='dont_know_pest_photo',
            field=models.ImageField(blank=True, null=True, upload_to=pest_scouting.models.dont_know_pest_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='dont_know_trap_photo',
            field=models.ImageField(blank=True, null=True, upload_to=pest_scouting.models.dont_know_trap_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='dont_know_variety_photo',
            field=models.ImageField(blank=True, null=True, upload_to=pest_scouting.models.dont_know_variety_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='dont_know_variety_voice',
            field=models.FileField(blank=True, null=True, upload_to=pest_scouting.models.dont_know_variety_voice_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='other_trap_photo',
            field=models.ImageField(blank=True, null=True, upload_to=pest_scouting.models.other_trap_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='overall_image',
            field=models.ImageField(blank=True, null=True, upload_to=pest_scouting.models.overall_image_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='voice_note',
            field=models.FileField(blank=True, null=True, upload_to=pest_scouting.models.weekly_record_voice_note_path),
        ),
    ]
