# Generated by Django 6.0.3 on 2026-05-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0019_alter_problemreport_photo_alter_trap_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='farm_size',
            field=models.FloatField(default=0.0),
        ),
    ]
