# Generated by Django 6.0.3 on 2026-05-12 09:09

import pest_scouting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pest_scouting', '0020_alter_farm_farm_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemreport',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=pest_scouting.models.problem_report_photo_path),
        ),
        migrations.AlterField(
            model_name='trap',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=pest_scouting.models.trap_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='disease_crop_stage',
            field=models.CharField(blank=True, choices=[('Flowering', 'Flowering'), ('Pin head', 'Pin head'), ('Golf size', 'Golf size'), ('Maturing', 'Maturing'), ('Mature', 'Mature')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='disease_detection_method',
            field=models.CharField(blank=True, choices=[('Self-observation', 'Self-observation'), ('Extension officer', 'Extension officer'), ('Agronomist', 'Agronomist'), ('KEPHIS inspector', 'KEPHIS inspector')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='dont_know_beneficial_insects_observed_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=pest_scouting.models.dont_know_beneficial_insects_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='dont_know_pest_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=pest_scouting.models.dont_know_pest_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='dont_know_trap_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=pest_scouting.models.dont_know_trap_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='dont_know_variety_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=pest_scouting.models.dont_know_variety_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='dont_know_variety_voice',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=pest_scouting.models.dont_know_variety_voice_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='other_trap_photo',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=pest_scouting.models.other_trap_photo_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='outcome',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='overall_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=pest_scouting.models.overall_image_path),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='variety',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='weeklyrecord',
            name='voice_note',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=pest_scouting.models.weekly_record_voice_note_path),
        ),
    ]
