# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations, models
from django.utils import timezone


def _format_case_code(n: int, year: int) -> str:
    return f'CSE-{n:04d}-{year}'


def backfill_case_codes(apps, schema_editor):
    Case = apps.get_model('case_management', 'Case')
    CaseCodeSequence = apps.get_model('case_management', 'CaseCodeSequence')

    cases = list(Case.objects.all().order_by('created_at', 'id'))
    counters: dict[int, int] = {}

    for c in cases:
        code = getattr(c, 'case_code', None)
        if code:
            continue
        year = c.created_at.year if getattr(c, 'created_at', None) else timezone.now().year
        counters[year] = counters.get(year, 0) + 1
        c.case_code = _format_case_code(counters[year], year)
        c.save(update_fields=['case_code'])

    for year, last_number in counters.items():
        obj, _ = CaseCodeSequence.objects.get_or_create(year=year)
        if obj.last_number < last_number:
            obj.last_number = last_number
            obj.save(update_fields=['last_number'])

    # Parse any pre-existing codes to prevent collisions (if any existed).
    existing = Case.objects.exclude(case_code__isnull=True).exclude(case_code='').values_list('case_code', flat=True)
    parsed: dict[int, int] = {}
    for code in existing:
        try:
            parts = str(code).split('-')
            if len(parts) != 3:
                continue
            n = int(parts[1])
            y = int(parts[2])
            parsed[y] = max(parsed.get(y, 0), n)
        except Exception:
            continue
    for y, n in parsed.items():
        obj, _ = CaseCodeSequence.objects.get_or_create(year=y)
        if obj.last_number < n:
            obj.last_number = n
            obj.save(update_fields=['last_number'])


class Migration(migrations.Migration):
    dependencies = [
        ('case_management', '0004_case_closed_at_case_diagnosis_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCodeSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='case_code',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.RunPython(backfill_case_codes, migrations.RunPython.noop),
    ]

