# Generated by Django 6.0.3 on 2026-04-21 08:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pest_scouting', '0004_farmblock_boundary_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advisory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('advisory_message', models.TextField()),
                ('actions_taken', models.CharField(blank=True, choices=[('🌿 Farm sanitation', '🌿 Farm sanitation'), ('✂️ Pruning', '✂️ Pruning'), ('🪤 Traps installed', '🪤 Traps installed'), ('🔧 Traps serviced', '🔧 Traps serviced'), ('💊 Chemical control', '💊 Chemical control'), ('🐞 Biological control', '🐞 Biological control')], max_length=100, null=True)),
                ('outcome', models.CharField(blank=True, choices=[('✅ Controlled', '✅ Controlled'), ('📉 Reduced', '📉 Reduced'), ('⚠️ Still present', '⚠️ Still present'), ('🔄 Follow-up needed', '🔄 Follow-up needed')], max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to=settings.AUTH_USER_MODEL)),
                ('weekly_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisories', to='pest_scouting.weeklyrecord')),
            ],
            options={
                'verbose_name_plural': 'Advisories',
                'ordering': ['-timestamp'],
            },
        ),
    ]
