# Generated by Django 6.0.3 on 2026-04-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='actions_taken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='advisory',
            name='outcome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
