# Generated by Django 6.0.3 on 2026-05-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory_services', '0002_alter_advisory_actions_taken_alter_advisory_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisory',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
