# Generated by Django 6.0.3 on 2026-05-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advisory_services', '0003_advisory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advisory',
            name='actions_taken',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='advisory',
            name='category',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='advisory',
            name='outcome',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
