import type { FarmerListRow } from '../types';
export const PLACEHOLDER_FARMERS: FarmerListRow[] = [
  {
    id: 'FRM-1024',
    name: 'Peter Mwangi',
    owner: 'Kangema Avocado Growers',
    location: 'Kangema',
    county: 'Murang\'a',
    ward: 'Kangema',
    primaryChannel: 'smartphone',
    weeklyScoutingLogs: [1, 1, 1, 1], // All weeks complete
    lastScoutingResult: {
      status: 'high-risk',
      finding: 'False Codling Moth',
    },
    exportEligibility: 'at-risk',
    totalAcres: 245,
    phone: '+254 722 345 678',
    lastInspection: 'Mar 14, 2026',
    overdueScouts: false,
  },
  {
    id: 'FRM-1023',
    name: 'Grace Wanjiku',
    owner: 'Gatanga Green Farms',
    location: 'Gatanga',
    county: 'Murang\'a',
    ward: 'Gatanga',
    primaryChannel: 'ussd',
    weeklyScoutingLogs: [1, 1, 0, 1], // Week 3 missing
    lastScoutingResult: {
      status: 'medium-risk',
      finding: 'Thrips Detected',
    },
    exportEligibility: 'at-risk',
    totalAcres: 189,
    phone: '+254 733 456 789',
    lastInspection: 'Mar 13, 2026',
    overdueScouts: true,
  },
  {
    id: 'FRM-1022',
    name: 'David Kipchirchir',
    owner: 'Tigoni Avocado Estates',
    location: 'Tigoni',
    county: 'Kiambu',
    ward: 'Limuru',
    primaryChannel: 'smartphone',
    weeklyScoutingLogs: [1, 1, 1, 1],
    lastScoutingResult: {
      status: 'no-pests',
      finding: 'No Pests Detected',
    },
    exportEligibility: 'ready',
    totalAcres: 312,
    phone: '+254 711 234 567',
    lastInspection: 'Mar 13, 2026',
    overdueScouts: false,
  },
  {
    id: 'FRM-1021',
    name: 'Faith Njeri',
    owner: 'Meru Sunrise Orchards',
    location: 'Meru Town',
    county: 'Meru',
    ward: 'Meru Central',
    primaryChannel: 'smartphone',
    weeklyScoutingLogs: [1, 1, 1, 1],
    lastScoutingResult: {
      status: 'no-pests',
      finding: 'Clean',
    },
    exportEligibility: 'ready',
    totalAcres: 156,
    phone: '+254 720 678 901',
    lastInspection: 'Mar 12, 2026',
    overdueScouts: false,
  },
  {
    id: 'FRM-1020',
    name: 'John Kimani',
    owner: 'Kiambu Highland Farms',
    location: 'Kiambu Town',
    county: 'Kiambu',
    ward: 'Kiambaa',
    primaryChannel: 'ussd',
    weeklyScoutingLogs: [1, 0, 1, 0], // Weeks 2 & 4 missing
    lastScoutingResult: {
      status: 'low-risk',
      finding: 'Minor Scale Insects',
    },
    exportEligibility: 'at-risk',
    totalAcres: 278,
    phone: '+254 712 567 890',
    lastInspection: 'Mar 12, 2026',
    overdueScouts: true,
  },
  {
    id: 'FRM-1019',
    name: 'Mary Wambui',
    owner: 'Nyeri Valley Growers',
    location: 'Nyeri Town',
    county: 'Nyeri',
    ward: 'Nyeri Central',
    primaryChannel: 'smartphone',
    weeklyScoutingLogs: [1, 1, 1, 1],
    lastScoutingResult: {
      status: 'no-pests',
      finding: 'Clean',
    },
    exportEligibility: 'ready',
    totalAcres: 198,
    phone: '+254 734 678 901',
    lastInspection: 'Mar 11, 2026',
    overdueScouts: false,
  },
  {
    id: 'FRM-1018',
    name: 'Samuel Omondi',
    owner: 'Bungoma Green Valley',
    location: 'Bungoma',
    county: 'Bungoma',
    ward: 'Bungoma East',
    primaryChannel: 'ussd',
    weeklyScoutingLogs: [0, 0, 0, 1], // Only week 4
    lastScoutingResult: {
      status: 'high-risk',
      finding: 'Root Rot Suspected',
    },
    exportEligibility: 'suspended',
    totalAcres: 134,
    phone: '+254 745 123 456',
    lastInspection: 'Mar 8, 2026',
    overdueScouts: true,
  },
  {
    id: 'FRM-1017',
    name: 'Jane Wambui',
    owner: 'Limuru Avocado Hub',
    location: 'Limuru',
    county: 'Kiambu',
    ward: 'Limuru Central',
    primaryChannel: 'smartphone',
    weeklyScoutingLogs: [1, 1, 1, 0], // Week 4 missing
    lastScoutingResult: {
      status: 'low-risk',
      finding: 'Leaf Minor',
    },
    exportEligibility: 'ready',
    totalAcres: 167,
    phone: '+254 723 987 654',
    lastInspection: 'Mar 10, 2026',
    overdueScouts: true,
  },
];
