import type { KnowledgeArticleSummary, KnowledgeCategoryRow } from '../types';
export const PLACEHOLDER_KB_ARTICLES: KnowledgeArticleSummary[] = [
  {
    id: 'KB-045',
    title: 'Avocado Thrips: Identification and Management',
    category: 'Pest Management',
    tags: ['Thrips', 'IPM', 'Treatment'],
    summary: 'Comprehensive guide to identifying and managing avocado thrips infestations, including life cycle, damage symptoms, and control strategies.',
    lastUpdated: 'Mar 10, 2026',
    views: 1247,
    severity: 'high',
    activeUses: 14,
    approvedContent: true,
    ussdCode: '102',
    chemicalGate: 'gated',
    ipmLevel: 3,
  },
  {
    id: 'KB-044',
    title: 'Phytophthora Root Rot Prevention and Control',
    category: 'Disease Management',
    tags: ['Root Rot', 'Prevention', 'Drainage'],
    summary: 'Best practices for preventing and controlling Phytophthora root rot, including soil management, irrigation practices, and treatment options.',
    lastUpdated: 'Mar 8, 2026',
    views: 982,
    severity: 'high',
    activeUses: 22,
    approvedContent: true,
    ussdCode: '205',
    chemicalGate: 'gated',
    ipmLevel: 3,
  },
  {
    id: 'KB-043',
    title: 'Integrated Pest Management (IPM) for Avocados',
    category: 'Best Practices',
    tags: ['IPM', 'Sustainable', 'Strategy'],
    summary: 'Overview of integrated pest management principles and how to implement IPM programs in avocado orchards.',
    lastUpdated: 'Mar 5, 2026',
    views: 1534,
    severity: 'low',
    activeUses: 8,
    approvedContent: true,
    ussdCode: null,
    chemicalGate: 'open',
    ipmLevel: 1,
  },
  {
    id: 'KB-042',
    title: 'Scouting Techniques for Early Detection',
    category: 'Field Operations',
    tags: ['Scouting', 'Detection', 'Training'],
    summary: 'Detailed scouting protocols and techniques for early detection of pests and diseases in avocado orchards.',
    lastUpdated: 'Mar 3, 2026',
    views: 876,
    severity: 'low',
    activeUses: 3,
    approvedContent: true,
    ussdCode: null,
    chemicalGate: 'open',
    ipmLevel: 1,
  },
  {
    id: 'KB-041',
    title: 'Understanding Persea Mite Biology and Behavior',
    category: 'Pest Biology',
    tags: ['Mites', 'Biology', 'Lifecycle'],
    summary: 'In-depth look at persea mite biology, lifecycle, and environmental factors affecting population dynamics.',
    lastUpdated: 'Feb 28, 2026',
    views: 654,
    severity: 'medium',
    activeUses: 11,
    approvedContent: true,
    ussdCode: '104',
    chemicalGate: 'open',
    ipmLevel: 2,
  },
  {
    id: 'KB-040',
    title: 'Anthracnose Disease Management',
    category: 'Disease Management',
    tags: ['Anthracnose', 'Fungicide', 'Prevention'],
    summary: 'Guidelines for managing anthracnose in avocados, including cultural practices and chemical control options.',
    lastUpdated: 'Feb 25, 2026',
    views: 723,
    severity: 'medium',
    activeUses: 17,
    approvedContent: true,
    ussdCode: '203',
    chemicalGate: 'gated',
    ipmLevel: 3,
  },
];

export const PLACEHOLDER_KB_CATEGORIES: KnowledgeCategoryRow[] = [
  { name: 'All Articles', count: 145 },
  { name: 'Pest Management', count: 42 },
  { name: 'Disease Management', count: 38 },
  { name: 'Best Practices', count: 28 },
  { name: 'Field Operations', count: 21 },
  { name: 'Pest Biology', count: 16 },
];
