import type { OutbreakMonitoringPayload } from '../types';

export const PLACEHOLDER_OUTBREAK_MONITORING: OutbreakMonitoringPayload = {
  alertTitle: 'Critical Outbreak Alert',
  alertMessage:
    "Avocado Thrips outbreak in Murang'a County showing rapid spread. 12 farms affected.",
  stats: {
    activeOutbreaks: 23,
    critical: 4,
    regionsAffected: 8,
    avgResponseTime: '18h',
  },
  outbreakTrends: [
    { date: 'Mar 1', thrips: 12, rootRot: 5, mites: 8, anthracnose: 3 },
    { date: 'Mar 3', thrips: 15, rootRot: 6, mites: 10, anthracnose: 4 },
    { date: 'Mar 5', thrips: 18, rootRot: 7, mites: 12, anthracnose: 5 },
    { date: 'Mar 7', thrips: 22, rootRot: 8, mites: 15, anthracnose: 6 },
    { date: 'Mar 9', thrips: 19, rootRot: 9, mites: 14, anthracnose: 7 },
    { date: 'Mar 11', thrips: 24, rootRot: 10, mites: 16, anthracnose: 8 },
    { date: 'Mar 13', thrips: 28, rootRot: 11, mites: 18, anthracnose: 9 },
    { date: 'Mar 15', thrips: 25, rootRot: 12, mites: 17, anthracnose: 10 },
  ],
  countyHeatMap: [
    { county: "Murang'a", intensity: 85, cases: 45, color: '#DC2626' },
    { county: 'Kiambu', intensity: 68, cases: 28, color: '#D97706' },
    { county: 'Meru', intensity: 42, cases: 19, color: '#FBBF24' },
    { county: 'Nyeri', intensity: 38, cases: 14, color: '#74C69D' },
    { county: 'Bungoma', intensity: 25, cases: 8, color: '#9CA3AF' },
    { county: 'Kakamega', intensity: 18, cases: 5, color: '#D1D5DB' },
    { county: 'Trans Nzoia', intensity: 15, cases: 4, color: '#E5E7EB' },
    { county: 'Embu', intensity: 12, cases: 3, color: '#F3F4F6' },
  ],
  activeOutbreaks: [
    {
      id: 'OUT-089',
      pest: 'Avocado Thrips',
      severity: 'critical',
      location: "Murang'a County",
      farmsAffected: 12,
      casesLinked: 45,
      firstDetected: 'Feb 28, 2026',
      trend: 'increasing',
    },
    {
      id: 'OUT-088',
      pest: 'Phytophthora Root Rot',
      severity: 'high',
      location: 'Kiambu County',
      farmsAffected: 8,
      casesLinked: 28,
      firstDetected: 'Mar 2, 2026',
      trend: 'stable',
    },
    {
      id: 'OUT-087',
      pest: 'Persea Mite',
      severity: 'medium',
      location: 'Meru County',
      farmsAffected: 6,
      casesLinked: 19,
      firstDetected: 'Mar 5, 2026',
      trend: 'decreasing',
    },
    {
      id: 'OUT-086',
      pest: 'Anthracnose',
      severity: 'medium',
      location: 'Nyeri County',
      farmsAffected: 4,
      casesLinked: 14,
      firstDetected: 'Mar 8, 2026',
      trend: 'increasing',
    },
  ],
};
