import type { ScoutingFeedItem } from '../types';
export const PLACEHOLDER_SCOUTING_FEED: ScoutingFeedItem[] = [
  {
    id: 'SF-2145',
    farmName: 'Wanjiru Farm',
    blockId: 'Block B',
    farmerName: 'Grace Wanjiru',
    severity: 'high',
    source: 'app',
    finding: 'False Codling Moth',
    status: 'detected',
    mediaPreview: 'https://images.unsplash.com/photo-1516253593875-bd7ba052fbc5?w=100&h=100&fit=crop',
    timestamp: '14 Mar, 08:30',
    reviewed: 'new',
    county: 'Murang\'a',
    assignedTo: 'Dr. James Kariuki',
  },
  {
    id: 'SF-2144',
    farmName: 'Kipchirchir Estates',
    blockId: 'Block A-12',
    farmerName: 'David Kipchirchir',
    severity: 'low',
    source: 'app',
    finding: 'No Pests Found',
    status: 'clean',
    mediaPreview: 'https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=100&h=100&fit=crop',
    timestamp: '14 Mar, 08:15',
    reviewed: 'reviewed',
    county: 'Kiambu',
  },
  {
    id: 'SF-2143',
    farmName: 'Mwangi Holdings',
    blockId: 'Block C',
    farmerName: 'Peter Mwangi',
    severity: 'high',
    source: 'ussd',
    finding: 'Root Rot Suspected',
    status: 'detected',
    ussdCode: '*104',
    timestamp: '14 Mar, 07:45',
    reviewed: 'new',
    county: 'Murang\'a',
    assignedTo: 'Dr. James Kariuki',
  },
  {
    id: 'SF-2142',
    farmName: 'Njeri Orchards',
    blockId: 'Block D-05',
    farmerName: 'Faith Njeri',
    severity: 'low',
    source: 'app',
    finding: 'No Pests Found',
    status: 'clean',
    mediaPreview: 'https://images.unsplash.com/photo-1590411806458-57ad1f1e8c4e?w=100&h=100&fit=crop',
    timestamp: '13 Mar, 16:20',
    reviewed: 'reviewed',
    county: 'Meru',
  },
  {
    id: 'SF-2141',
    farmName: 'Kimani Avocado Co.',
    blockId: 'Block F-03',
    farmerName: 'John Kimani',
    severity: 'medium',
    source: 'ussd',
    finding: 'Thrips Detected',
    status: 'detected',
    ussdCode: '*105',
    timestamp: '13 Mar, 14:10',
    reviewed: 'under-review',
    county: 'Kiambu',
    assignedTo: 'Dr. Sarah Mwangi',
  },
  {
    id: 'SF-2140',
    farmName: 'Wambui Valley Farm',
    blockId: 'Block E-02',
    farmerName: 'Mary Wambui',
    severity: 'low',
    source: 'app',
    finding: 'No Pests Found',
    status: 'clean',
    mediaPreview: 'https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=100&h=100&fit=crop',
    timestamp: '13 Mar, 11:45',
    reviewed: 'reviewed',
    county: 'Nyeri',
  },
  {
    id: 'SF-2139',
    farmName: 'Omondi Green Valley',
    blockId: 'Block G',
    farmerName: 'Samuel Omondi',
    severity: 'high',
    source: 'ussd',
    finding: 'Fruit Fly Infestation',
    status: 'detected',
    ussdCode: '*102',
    timestamp: '13 Mar, 09:30',
    reviewed: 'new',
    county: 'Bungoma',
  },
  {
    id: 'SF-2138',
    farmName: 'Kariuki Farms',
    blockId: 'Block H-08',
    farmerName: 'Joseph Kariuki',
    severity: 'medium',
    source: 'app',
    finding: 'Scale Insects',
    status: 'detected',
    mediaPreview: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=100&h=100&fit=crop',
    timestamp: '12 Mar, 15:50',
    reviewed: 'new',
    county: 'Kiambu',
  },
  {
    id: 'SF-2137',
    farmName: 'Wanjiru Estates',
    blockId: 'Block K-01',
    farmerName: 'Lucy Wanjiru',
    severity: 'low',
    source: 'app',
    finding: 'No Pests Found',
    status: 'clean',
    mediaPreview: 'https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=100&h=100&fit=crop',
    timestamp: '12 Mar, 13:20',
    reviewed: 'reviewed',
    county: 'Embu',
  },
  {
    id: 'SF-2136',
    farmName: 'Mutua Orchards',
    blockId: 'Block J',
    farmerName: 'Daniel Mutua',
    severity: 'medium',
    source: 'ussd',
    finding: 'Leaf Miner Detected',
    status: 'detected',
    ussdCode: '*108',
    timestamp: '12 Mar, 10:15',
    reviewed: 'under-review',
    county: 'Machakos',
    assignedTo: 'Dr. John Maina',
  },
  {
    id: 'SF-2135',
    farmName: 'Kamau Farm',
    blockId: 'Block C',
    farmerName: 'James Kamau',
    severity: 'high',
    source: 'app',
    finding: 'False Codling Moth Detected',
    status: 'detected',
    mediaPreview: 'https://images.unsplash.com/photo-1516253593875-bd7ba052fbc5?w=100&h=100&fit=crop',
    timestamp: '12 Mar, 09:05',
    reviewed: 'new',
    county: 'Kiambu',
    assignedTo: 'Dr. James Kariuki',
  },
  {
    id: 'SF-2134',
    farmName: 'Njoroge Orchards',
    blockId: 'Block M-07',
    farmerName: 'Anne Njoroge',
    severity: 'medium',
    source: 'ussd',
    finding: 'Anthracnose Detected',
    status: 'detected',
    ussdCode: '*103',
    timestamp: '11 Mar, 16:40',
    reviewed: 'new',
    county: 'Nyeri',
  },
];
