# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0005_seed_demo_farmer_profile_990011'),
        ('kephis_quarantine', '0005_incident_workflow_and_custody_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChinaFarmIdSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ChinaFarmCertification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('china_farm_id', models.CharField(blank=True, default=None, max_length=32, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='draft', max_length=16)),
                ('inspected_at', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('management_insights', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='china_certifications', to='api.farmerprofile')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='china_farm_certifications_issued', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chinafarmcertification',
            index=models.Index(fields=['farmer', '-updated_at'], name='kephis_quar_farmer__3b6b09_idx'),
        ),
        migrations.AddIndex(
            model_name='chinafarmcertification',
            index=models.Index(fields=['status', '-updated_at'], name='kephis_quar_status__d51739_idx'),
        ),
    ]

