# Generated by GPT-5.2 on 2026-04-21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('kephis_quarantine', '0006_china_farm_certification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chinafarmcertification',
            name='export_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chinafarmcertification',
            name='export_approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='china_farm_export_approvals',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]

